{

  default:graphqlTestFilteredView (filter: {title: "A"}) {
    results {
      entityLabel
    }
  }

  multi:graphqlTestFilteredView (filter: {field_tags: ["1", "2"]}) {
    results {
      entityLabel
    }
  }

  complex:graphqlTestFilteredView(filter: {node_type:{test:"test"}}) {
    results {
      entityLabel
    }
  }

}
