{

  default:graphqlTestFilteredView (filter: {title: "A"}) {
    entityLabel
  }

  multi:graphqlTestFilteredView (filter: {field_tags: ["1", "2"]}) {
    entityLabel
  }

  complex:graphqlTestFilteredView(filter: {node_type:{test:"test"}}) {
    entityLabel
  }

}
