{

  default:graphqlTestSortedView {
    results {
      entityLabel
    }
  }

  asc:graphqlTestSortedView(sortBy: TITLE) {
    results {
      entityLabel
    }
  }

  desc:graphqlTestSortedView(sortBy: TITLE, sortDirection: DESC) {
    results {
      entityLabel
    }
  }

  asc_nid:graphqlTestSortedView(sortBy: NID, sortDirection: ASC) {
    results {
      entityLabel
    }
  }

  desc_nid:graphqlTestSortedView(sortBy: NID, sortDirection: DESC) {
    results {
      entityLabel
    }
  }
}