<?php

/**
 * @file
 * Install, update and uninstall functions for the GraphQL module.
 */

declare(strict_types=1);

use Drupal\graphql\Entity\Server;
use Drupal\graphql\Plugin\LanguageNegotiation\OperationLanguageNegotiation;
use GraphQL\Error\DebugFlag;

/**
 * Implements hook_uninstall().
 */
function graphql_uninstall(): void {
  // Remove the config keys set in GraphQLConfigOverrides::loadOverrides().
  /** @var \Drupal\Core\Config\ConfigFactoryInterface $configFactory */
  $configFactory = \Drupal::getContainer()->get('config.factory');
  $languageTypes = $configFactory->getEditable('language.types');
  if ($negotiation = $languageTypes->get('negotiation')) {
    foreach (array_keys($negotiation) as $type) {
      unset($negotiation[$type]['enabled'][OperationLanguageNegotiation::METHOD_ID]);
    }
    $languageTypes->set('negotiation', $negotiation)->save();
  }
}

/**
 * Implements hook_update_dependencies().
 */
function graphql_update_dependencies(): array {
  // Prevent type errors when the wrong order of update functions is executed.
  // Our graphql update function must run first.
  $dependencies['admin_toolbar_tools'][8203] = [
    'graphql' => 50001,
  ];
  return $dependencies;
}

/**
 * Update GraphQL Server debug configuration value.
 */
function graphql_update_8001(): void {
  // The `debug` config item has changed to `debug_flag`. It is no longer a
  // boolean toggle but instead a set of flags providing more control. In this
  // case we default to debug messages and a backtrace in case debugging was
  // enabled and just unselect all flags otherwise.
  $servers = Server::loadMultiple();
  foreach ($servers as $server) {
    // There is no need to unset `debug` as its property no longer exists so it
    // will not get persisted.
    $debugEnabled = (bool) $server->get('debug');
    $server->set(
      'debug_flag',
      $debugEnabled ? DebugFlag::INCLUDE_DEBUG_MESSAGE | DebugFlag::INCLUDE_TRACE : DebugFlag::NONE
    );
    $server->save();
  }
}

/**
 * Empty update that was removed again.
 */
function graphql_update_8400(): void {
}

/**
 * Empty update that was removed again.
 */
function graphql_update_10400(): void {
}

/**
 * Remove graphql.settings legacy configuration.
 */
function graphql_update_50000(): void {
  \Drupal::configFactory()->getEditable('graphql.settings')->delete();
}

/**
 * Set the query_depth and query_complexity to integer types.
 */
function graphql_update_50001(): void {
  // Load config objects instead of full config entities to avoid fatal errors.
  $server_ids = \Drupal::configFactory()->listAll('graphql.graphql_servers.');
  foreach ($server_ids as $id) {
    $server = \Drupal::configFactory()->getEditable($id);
    $should_update = FALSE;
    if (!is_int($server->get('query_depth'))) {
      $server->set('query_depth', (int) $server->get('query_depth'));
      $should_update = TRUE;
    }
    if (!is_int($server->get('query_complexity'))) {
      $server->set('query_complexity', (int) $server->get('query_complexity'));
      $should_update = TRUE;
    }
    if ($should_update) {
      $server->save();
    }
  }
}
