query ($nid: Int!) {
  node:nodeQuery(filter: {nid: $nid}) {
    entities {
      entityId,
      entityUuid,
      entityLabel,
      entityType,
      entityBundle,
      entityLanguage {
        id,
        name,
        direction,
        weight
      },
      entityRoute:entityUrl {
        internalPath:path,
        aliasedPath:alias
      },
      entityOwner {
        entityLabel
      }
      entityTranslation(language: fr) {
        entityLabel
      }
      entityPublished
      entityCreated
      entityChanged
      viewAccess:entityAccess(operation: "view")
      updateAccess:entityAccess(operation: "update")
      deleteAccess:entityAccess(operation: "delete")
    }
  }
}
