query ($nid: String!) {
  node:nodeQuery(filter: {
    conditions: [{
      field: "nid"
      value: [$nid]
    }]
  }) {
    entities {
      entityId
      entityUuid
      entityLabel
      entityType
      entityBundle
      entityLanguage {
        id
        name
        direction
        weight
      }
      entityUrl {
        path
      }
      entityTranslation(language: FR) {
        entityLabel
      }
      ... on EntityOwnable {
        entityOwner {
          entityLabel
        }
      }
      ... on EntityPublishable {
        entityPublished
      }
      entityCreated
      entityChanged
      viewAccess:entityAccess(operation: "view")
      updateAccess:entityAccess(operation: "update")
      deleteAccess:entityAccess(operation: "delete")
    }
  }
}
