query {
  a:route(path: "/graphql/test/a") {
    ... on InternalUrl {
      name:routeNameContext
    }
  }
  b:route(path: "/graphql/test/b") {
    ... on InternalUrl {
      name:routeNameContext
    }
  }
}