query {
  a:nodeQuery(type: "a") {
    count
    entities {
      uuid:entityUuid
    }
  }

  b:nodeQuery(type: "b") {
    count
    entities {
      uuid:entityUuid
    }
  }

  limit:nodeQuery(type: "a", limit: 2) {
    count
    entities {
      uuid:entityUuid
    }
  }

  offset:nodeQuery(type: "a", offset: 1) {
    count
    entities {
      uuid:entityUuid
    }
  }

  offset_limit:nodeQuery(type: "a", offset: 1, limit: 1) {
    count
    entities {
      uuid:entityUuid
    }
  }
}