query {
  a:nodeQuery(type: "a") {
    uuid:entityUuid
  }

  b:nodeQuery(type: "b") {
    uuid:entityUuid
  }

  limit:nodeQuery(type: "a", limit: 2) {
    uuid:entityUuid
  }

  offset:nodeQuery(type: "a", offset: 1) {
    uuid:entityUuid
  }

  offset_limit:nodeQuery(type: "a", offset: 1, limit: 1) {
    uuid:entityUuid
  }
}