mutation($node: NodeArticleCreateInput!) {
  create:createNodeArticle (input: $node) {
    entity {
      uuid:entityUuid
    }
    errors
    violations {
      code
      path
      message
    }
  }
}