query {
  a:nodeQuery(filter: {
    conditions: [{
      field: "type"
      value: ["a"]
    }]
  }) {
    count
    entities {
      uuid:entityUuid
    }
  }

  b:nodeQuery(filter: {
    conditions: [{
      field: "type"
      value: ["b"]
    }]
  }) {
    count
    entities {
      uuid:entityUuid
    }
  }

  limit:nodeQuery(filter: {
    conditions: [{
      field: "type"
      value: ["a"]
    }]
  }, limit: 2) {
    count
    entities {
      uuid:entityUuid
    }
  }

  offset:nodeQuery(filter: {
    conditions: [{
      field: "type"
      value: ["a"]
    }]
  }, offset: 1) {
    count
    entities {
      uuid:entityUuid
    }
  }

  offset_limit:nodeQuery(filter: {
    conditions: [{
      field: "type"
      value: ["a"]
    }]
  }, offset: 1, limit: 1) {
    count
    entities {
      uuid:entityUuid
    }
  }

  all_nodes:nodeQuery {
    count
    entities {
      uuid:entityUuid
    }
  }
}