query ($path: String!) {
  route:route(path: $path) {
    ... on EntityCanonicalUrl {
      node:entity {
        image {
          alt
          title
          width
          height
          entity {
            url
          }
          thumbnailImage:derivative(style: thumbnail) {
            width
            height
            url
          }
        }
      }
    }
  }
}
