query {
  ok:route(path: "/graphql-request/test/ok") {
    ... on InternalUrl {
      request {
        code
        content
      }
    }
  }

  redirect:route(path: "/graphql-request/test/redirect") {
    ... on InternalUrl {
      request {
        code
        location:header(key: "location")
      }
    }
  }
}