query {
  languages:availableLanguages {
    id
    name
    isDefault
    isLocked
    direction
    weight
    argument
  }
  frontpage:route(path: "/") {
    languageSwitchLinks {
      langcode
      title
      isActive
      url {
        asString
      }
    }
  }
}
