query {
  languages:availableLanguages {
    id
    name
    isDefault
    isLocked
    direction
    weight
    argument
  }

  default:route(path: "/graphql/test/a") {
    ... LanguageFragment
  }

  en:route(path: "/en/graphql/test/a") {
    ... LanguageFragment
  }

  fr:route(path: "/fr/graphql/test/a") {
    ... LanguageFragment
  }
}

fragment LanguageFragment on Url {
  languageInterfaceContext {
    ... on Language {
      id
      name
      isDefault
      isLocked
      direction
      weight
    }
  }
}