query {
  route(path: "/") {
    ... on InternalUrl {
      links:languageSwitchLinks {
        language {
          id
        }
        title
        active
        url {
          path
        }
      }
    }
  }
}
