query {
  route:route(path: "/graphql/test/a") {
    path

    ... on InternalUrl {
      alias:pathAlias
      internal:pathInternal
    }
  }
  denied:route(path: "/graphql/test/c") {
    path

    ... on InternalUrl {
      alias:pathAlias
      internal:pathInternal
    }
  }
}