query {
  route:route(path: "/graphql/test/a") {
    path
    alias:pathAlias
    internal:pathInternal
  }
  denied:route(path: "/graphql/test/c") {
    path
    alias:pathAlias
    internal:pathInternal
  }
}