<?php

/**
 * @file
 * GraphQL content test hook implementations.
 */

/**
 * Implements hook_entity_extra_field_info().
 *
 * {@inheritdoc}
 */
function graphql_content_test_entity_extra_field_info() {
  $extra = array();

  $extra['node']['test']['display']['test'] = array(
    'label' => t('Test'),
    'description' => t('A virtual test field'),
    'weight' => 0,
  );
  return $extra;
}

/**
 * Implements hook_entity_display_build_alter().
 */
function graphql_content_test_entity_display_build_alter(&$build, $context) {
  /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display */
  $display = $context['display'];
  if ($display->getComponent('test')) {
    $build['test'] = [
      '#type' => 'markup',
      '#markup' => 'This is a test.',
    ];
  }
}
