query {
  info:menuByName(name: "test") {
    name
    description
  }
  menu:menuByName(name: "test") {
    links {
      ... Item
      links {
        ... Item
      }
    }
  }
}

fragment Item on MenuLink {
  label
  attribute(key: "test")
  route:url {
    path
    routed
  }
}
