<?php

/**
 * Implements hook_theme().
 */
function graphql_twig_test_theme($existing, $type, $theme, $path) {
  return [
    'graphql_echo' => [
      'variables' => [
        'input' => NULL,
      ],
    ],
    'graphql_garage' => [
      'variables' => [],
    ],
    'graphql_vehicle' => [
      'variables' => [
        'vehicle' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function graphql_twig_test_theme_suggestions_graphql_vehicle_alter(array &$suggestions, array $variables, $hook) {
  $suggestions[] = $hook . '__' . strtolower($variables['vehicle']['type']);
}
