query ($path: String!) {
  route:route(path: $path) {
    node:entity {
      image {
        alt
        title
        originalImage {
          fileSize
          mimeType
          width
          height
          url
        }
        thumbnailImage {
          fileSize
          mimeType
          width
          height
          url
        }
      }
    }
  }
}
