query ($path: String!, $responsiveStyle: String!) {
  route:route(path: $path) {
    node:entity {
      image {
        alt
        title
        fileSize
        mimeType
        width
        height
        url
        responsive(styleId: $responsiveStyle)
        thumbnailImage: derivative(style: thumbnail) {
          width
          height
          url
        }
      }
    }
  }
}
