query {
  content:blocksByRegion(region: "content") {
    __typename
  }
  route:route(path: "/user/login") {
    content:blocksByRegion(region: "content") {
      __typename
    }

    sidebar:blocksByRegion(region: "sidebar_first") {
      ... on BlockContentBasic {
        __typename
        body {
          value
        }
      }
    }
  }
}