query ($path: String!) {
  route:route(path: $path) {
    node:nodeContext {
      entityId,
      entityUuid,
      entityLabel,
      entityType,
      entityBundle,
      entityLanguage {
        id,
        name,
        direction,
        weight
      },
      entityRoute:entityUrl {
        internalPath:path,
        aliasedPath:alias
      },
      entityTranslation(language: fr) {
        entityLabel
      }
    }
    node_test:nodeContext {
      ... on NodeTest {
        entityId,
        entityUuid,
        entityLabel,
        entityType,
        entityBundle,
        entityLanguage {
          id,
          name,
          direction,
          weight
        },
        entityRoute:entityUrl {
          internalPath:path,
          aliasedPath:alias
        },
        entityTranslation(language: fr) {
         entityLabel
        }
      }
    }
  }
}
