query {
  route(path: "http://graphql.drupal/xml") {
    request {
      xml {
        ... on XMLElement {
          node:xpathToEntity(type: "node", query:"a/@data-uuid") {
            uuid:entityUuid
          }
        }
      }
    }
  }
}