query ($path: String!) {
  route(path: $path) {
    entity {
      ... on EntityTestWithBundleGraphql {
        xml {
          paragraphs:xpath(query: "p") {
            name
          }
        }
      }
    }
  }
}
