query ($path: String!) {
  route(path: $path) {
    entity {
      ... on EntityTestWithBundleGraphql {
        xml {
          div:xpath(query:"/div") {
            content
          }
          paragraphs:xpath(query: "p") {
            content
            spans:xpath(query: "span") {
              content
            }
          }
        }
      }
    }
  }
}
