<?php
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function graphql_graphiql_theme() {
  return [
    'page__graphql_explorer' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_graphql_schema_operations().
 */
function graphql_graphiql_graphql_schema_operations($pluginId, array $pluginDefinition) {
  $operations = [];

  if (\Drupal::currentUser()->hasPermission('use graphql explorer')) {
    $operations['explorer'] = [
      'title' => 'Explorer',
      'weight' => 10,
      'url' => Url::fromRoute("graphql_graphiql.explorer.$pluginId"),
    ];
  }

  return $operations;
}
