<?php
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function graphql_voyager_theme() {
  return [
    'page__graphql_voyager' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_graphql_schema_operations().
 */
function graphql_voyager_graphql_schema_operations($pluginId, array $pluginDefinition) {
  $operations = [];

  if (\Drupal::currentUser()->hasPermission('use graphql voyager')) {
    $operations['voyager'] = [
      'title' => 'Voyager',
      'weight' => 10,
      'url' => Url::fromRoute("graphql_voyager.voyager.$pluginId"),
    ];
  }

  return $operations;
}