<?php

namespace Drupal\graphql_image\Plugin\GraphQL\Types;

use Drupal\graphql_core\GraphQL\TypePluginBase;
use Drupal\graphql_core\GraphQLSchemaManagerInterface;

/**
 * GraphQL Type for Drupal image derivatives.
 *
 * @GraphQLType(
 *   id = "image_resource",
 *   name = "ImageResource",
 * )
 */
class ImageResource extends TypePluginBase {

  protected function buildFields(GraphQLSchemaManagerInterface $schemaManager)
  {
    return parent::buildFields($schemaManager); // TODO: Change the autogenerated stub
  }

}
