query ($test2NodeId: String!) {

  # graphql_test:contextual_title_arg
  title_arg0:graphqlTestContextualTitleArgView {
    results {
      entityId
    }
  }

  title_arg1:graphqlTestContextualTitleArgView (contextualFilter: {title: "X"}) {
    results {
      entityId
    }
  }

  # graphql_test:contextual_node
  node0:graphqlTestContextualNodeView {
    results {
      entityId
    }
  }

  node1:graphqlTestContextualNodeView (contextualFilter: {nid: "X"}) {
    results {
      entityId
    }
  }

  node2:nodeById (id: "1", language: en) {
    ... on Node {
      graphqlTestContextualNodeView {
        results {
          entityId
        }
      }
    }
  }
  node3:nodeById (id: "1", language: en) {
    ... on Node {
      graphqlTestContextualNodeView (contextualFilter: {nid: "X"}) {
        results {
          entityId
        }
      }
    }
  }
  node4:nodeById (id: "1", language: en) {
    ... on NodeTest {
      graphqlTestContextualNodeView {
        results {
          entityId
        }
      }
    }
  }
  node5:nodeById (id: "1", language: en) {
    ... on NodeTest {
      graphqlTestContextualNodeView (contextualFilter: {nid: "X"}) {
        results {
          entityId
        }
      }
    }
  }

  # graphql_test:contextual_nodetest
  nodetest0:graphqlTestContextualNodetestView {
    results {
      entityId
    }
  }

  nodetest1:graphqlTestContextualNodetestView (contextualFilter: {nid: "X"}) {
    results {
      entityId
    }
  }

  nodetest2:nodeById (id: "1", language: en) {
    ... on NodeTest {
      graphqlTestContextualNodetestView {
        results {
          entityId
        }
      }
    }
  }

  nodetest3:nodeById (id: "1", language: en) {
    ... on NodeTest {
      graphqlTestContextualNodetestView (contextualFilter: {nid: "X"}) {
        results {
          entityId
        }
      }
    }
  }

  # graphql_test:contextual_node_and_nodetest
  node_and_nodetest0:graphqlTestContextualNodeAndNodetestView {
    results {
      entityId
    }
  }

  node_and_nodetest1:graphqlTestContextualNodeAndNodetestView (contextualFilter: {nid: "X", nid_1: "X"}) {
    results {
      entityId
    }
  }

  node_and_nodetest2:nodeById (id: $test2NodeId, language: en) {
    ... on Node {
      graphqlTestContextualNodeAndNodetestView {
        results {
          entityId
        }
      }
    }
  }
  node_and_nodetest3:nodeById (id: $test2NodeId, language: en) {
    ... on Node {
      graphqlTestContextualNodeAndNodetestView (contextualFilter: {nid: "X", nid_1: "X"}) {
        results {
          entityId
        }
      }
    }
  }

  node_and_nodetest4:nodeById (id: "1", language: en) {
    ... on NodeTest {
      graphqlTestContextualNodeAndNodetestView {
        results {
          entityId
        }
      }
    }
  }

  node_and_nodetest5:nodeById (id: "1", language: en) {
    ... on NodeTest {
      graphqlTestContextualNodeAndNodetestView (contextualFilter: {nid: "X", nid_1: "X"}) {
        results {
          entityId
        }
      }
    }
  }

}
